import type { Metadata } from "next";
import "./globals.css";

import { getSiteSettings } from "./queries/getSiteSettings";
import { generateMetadata as genMeta } from "./queries/generateMetaData";

export async function generateMetaData() {
  const settings = await getSiteSettings();

  return genMeta({
    siteName: settings?.siteName,
    siteUrl: settings?.siteUrl,
    defaultSeo: settings?.defaultSeo,
  });
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
