import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import SmoothScroll from "./components/utils/smoothScroll";
import { CartProvider } from "./context/CartContext";
import CartDrawer from "./components/shop/CartDrawer";

import { getSiteSettings } from "./queries/getSiteSettings";

const vagRound = localFont({
  src: "../public/fonts/OPTIVagRound-Bold.otf",
  variable: "--font-vag",
  display: "swap",
  fallback: ["Nunito", "Arial Rounded MT Bold", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create next app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSiteSettings();

  const areaServed = settings?.serviceAreas?.length
    ? settings.serviceAreas.map((area: string) => ({ "@type": "City", name: area }))
    : [{ "@type": "AdministrativeArea", name: "Central Texas" }];

  return (
    <html lang="en" className={vagRound.variable}>
      <body className="antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              name: settings?.siteName,
              description: settings?.localBusinessDescription,
              url: settings?.siteUrl,
              telephone: settings?.phone || undefined,
              priceRange: settings?.priceRange || undefined,
              sameAs: settings?.sameAs?.length ? settings.sameAs : undefined,
              areaServed,
              knowsAbout: settings?.knowsAbout,
            }),
          }}
        />
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-GJTNMW67JS" strategy="afterInteractive" />
        <Script id="google-analytics" strategy="afterInteractive">{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-GJTNMW67JS');
        `}</Script>
        <SmoothScroll />
        <CartProvider>
          {children}
          <CartDrawer />
        </CartProvider>
      </body>
    </html>
  );
}
