import page from './documents/page'
import mainMenu from './documents/mainMenu'
import blogList from './documents/blogList'
import contentBuilder from './fields/contentBuilder'
import row from './types/row'
import column from './types/column'
import heading from './fields/heading'
import imageField from './fields/imageField'
import advancedText from './fields/advancedText'
import button from './fields/button'
import buttonStyles from './fields/buttonStyles'
import link from './fields/link' 
import publishedDate from './fields/publishedDate'  
import menuItem from './fields/menuItem'
import hero from './types/hero'
import card from './objects/card'
import form from './objects/form'
import seo from './objects/seo'
import siteSettings from './documents/siteSettings'
import innerRow from './types/innerRow'
import pill from  './fields/pill'
import footer from './documents/footer'

export const schemaTypes = [ page, mainMenu, seo, pill, footer, blogList, innerRow, publishedDate, menuItem, card, row, hero, contentBuilder, 
    heading, column, imageField, advancedText, button, siteSettings, buttonStyles, form, link ]
